{
  "mitigation": "Mitigation for this issue is either not available or the currently available options do not meet the Red Hat Product Security criteria comprising ease of use and deployment, applicability to widespread installation base or stability.",
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2024-01-10T00:00:00Z",
      "advisory": "RHSA-2024:0114",
      "package": "python3-0:3.6.8-56.el8_9.2",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2024-01-10T00:00:00Z",
      "advisory": "RHSA-2024:0114",
      "package": "python3-0:3.6.8-56.el8_9.2",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8.6 Extended Update Support",
      "release_date": "2024-01-25T00:00:00Z",
      "advisory": "RHSA-2024:0430",
      "package": "python3-0:3.6.8-47.el8_6.4",
      "cpe": "cpe:/a:redhat:rhel_eus:8.6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8.8 Extended Update Support",
      "release_date": "2024-01-30T00:00:00Z",
      "advisory": "RHSA-2024:0586",
      "package": "python3-0:3.6.8-51.el8_8.4",
      "cpe": "cpe:/a:redhat:rhel_eus:8.8"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "python",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "python",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python3",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "gimp:flatpak/python2",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "inkscape:flatpak/python2",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "python27:2.7/python2",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "python3.11",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "python36:3.6/python36",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "python39:3.9/python39",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "python3.11",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "python3.9",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Not affected",
      "package_name": "rh-python38-python",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-08-22T00:00:00Z",
  "bugzilla": {
    "description": "python: DoS when processing malformed Apple Property List files in binary format",
    "id": "2249750",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2249750"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-400",
  "statement": "Versions of python36:3.6/python36 as shipped with Red Hat Enterprise Linux 8 are marked as 'Not affected' as they just provide \"symlinks\" to the main python3 component, which provides the actual interpreter of the Python programming language.",
  "acknowledgement": "",
  "name": "CVE-2022-48564",
  "document_distribution": "",
  "details": [
    "read_ints in plistlib.py in Python through 3.9.1 is vulnerable to a potential DoS attack via CPU and RAM exhaustion when processing malformed Apple Property List files in binary format.",
    "A vulnerability was found in the Python core plistlib library within the read_ints() function in the plistlib.py file. In malformed input, the implementation can be manipulated to create an argument for struct.unpack(). This issue can lead to excessive CPU and memory consumption, resulting in a MemError, as it constructs the 'format' argument for unpack(). This flaw allows an attacker to employ a binary plist input, potentially executing a denial of service (DoS) attack by exhausting CPU and RAM resources."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-48564\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-48564\nhttps://bugs.python.org/issue42103\nhttps://github.com/python/cpython/issues/86269"
  ]
}